In [100]:
!pip install pandas
import pandas
import pandas as pd
from pandas import DataFrame as df


Defaulting to user installation because normal site-packages is not writeable


In [101]:

import os 
os.getcwd
directory = "Buzzaibhuvana"
parent_dir = "D:/Buzzaibhuvana/"
path = os.path.join(parent_dir, directory) 
os.mkdir(path) 
os.chdir("new/Desktop/directory")


FileNotFoundError: [Errno 2] No such file or directory: 'D:/Buzzaibhuvana/Buzzaibhuvana'

In [102]:
'''Arithemetic operators'''
102+32
100-47
90*4
2**3
4/2
4%2

0

In [103]:
'''Assignment operators'''
a=5.3
x=[1,2,3]
x[0]=1

In [104]:
'''Numeric operators'''
3==3

True

In [105]:
3!=3

False

In [106]:
3<=4

True

In [107]:
'''logical operators'''
-(2==2)

-1

In [108]:
(1!=1)^(1^1)

0

In [109]:
(1!=1)&(1<1)

False

In [110]:
(1>=1)|(1<1)

True

In [113]:
'''list'''
x=[1,2,2,4,33]
x.sort()
print(x.sorted(x))
print(x.reversed())
print(reversed(x))
x.count(2)

AttributeError: 'list' object has no attribute 'sorted'

In [114]:
x=['a','b','c']
print(x[0],x[-1],x[1:3],x[:3],x[:3])

a c ['b', 'c'] ['a', 'b', 'c'] ['a', 'b', 'c']


In [115]:
b=[1,2,3]
print(x+b)
print(3*b)
print(b*3)

['a', 'b', 'c', 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [116]:
'''Dictionaries'''
d={'a':1,'b':4,'c':3,'d':7}
print(d.keys(),d.values(),d['a'])

dict_keys(['a', 'b', 'c', 'd']) dict_values([1, 4, 3, 7]) 1


In [117]:
'''Numpy arrays'''
import numpy as np

In [118]:
np.array([1,2,3,5,6,7,9])
np.arange(1,5)

array([1, 2, 3, 4])

In [119]:
np.arange(1,5,2)

array([1, 3])

In [120]:
print(np.repeat([9,8,7],3),np.tile([9,8,7],3))

[9 9 9 8 8 8 7 7 7] [9 8 7 9 8 7 9 8 7]


In [121]:
'''Math functions and methods'''
x=[1,2,3,4,5]
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [122]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [123]:
np.max(x)

5

In [124]:
np.sum(x)

15

In [125]:
np.mean(x)

3.0

In [126]:
np.quantile(x,0.5)

3.0

In [127]:
np.round(x,2)

array([1, 2, 3, 4, 5])

In [128]:
np.var(x)

2.0

In [129]:
np.std(x)

1.4142135623730951

In [130]:
'''characters and strings'''
print("He said, \"Datacamp\"")

He said, "Datacamp"


In [131]:
x="hii"
print(x[0],x[:2],x[1:3])

h hi ii


In [132]:
s="Python"
print(x+s)
print(x.split("i"))

hiiPython
['h', '', '']


In [133]:
'''Getting started with data frames'''
df=pd.DataFrame({
    'a':[1,2,3],
    'b':np.array([1,2,3]),
    'c': 'df'})
print(df)

   a  b   c
0  1  1  df
1  2  2  df
2  3  3  df


In [134]:
df.iloc[2]

a     3
b     3
c    df
Name: 2, dtype: object

In [135]:
df['c']

0    df
1    df
2    df
Name: c, dtype: object

In [136]:
df[['a','b']]

a  b
0  1  1
1  2  2
2  3  3

In [137]:
df.iloc[:,2]

0    df
1    df
2    df
Name: c, dtype: object

In [138]:
df.iloc[1,2]

'df'

In [139]:
'''Manipulating DF'''
x=pd.DataFrame([
    {'a':1,'b':3,'c':2},
    {'c':9,'2':7,'9':a}])
print(x)

     a    b  c    2    9
0  1.0  3.0  2  NaN  NaN
1  NaN  NaN  9  7.0  5.3


In [140]:
pd.concat([df,x])

a    b   c    2    9
0  1.0  1.0  df  NaN  NaN
1  2.0  2.0  df  NaN  NaN
2  3.0  3.0  df  NaN  NaN
0  1.0  3.0   2  NaN  NaN
1  NaN  NaN   9  7.0  5.3

In [141]:
pd.concat([df,x],axis="c")

ValueError: No axis named c for object type DataFrame

In [142]:
df.drop(columns=['a'])

b   c
0  1  df
1  2  df
2  3  df

In [143]:
df.rename(columns={"a":"B"})

B  b   c
0  1  1  df
1  2  2  df
2  3  3  df

In [147]:
DataFrame.mean(x)

a    1.0
b    3.0
c    5.5
2    7.0
9    5.3
dtype: float64

In [149]:
df.sort_value(by="a")

SpecificationError: nested renamer is not supported

In [150]:
DataFrame.drop_duplicates(df,x)

KeyError: Index(['2', '9'], dtype='object')